Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace webapp.Controllers
{
    public class DashboardController : Controller
    {
        //ApiService api = new ApiService();
        // GET: /Dashboard/
        // Auth here
        //public IActionResult Index()
        //{
        //    //DashboardData dd = new DashboardData();
        //    ApiService api = new ApiService();

        //    return View();
        //}

        public IActionResult Index()
        {

            return View();
        }
    }
}

Controllers/InternshipController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using webapp.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace webapp.Controllers
{
    public class InternshipController : Controller
    {
        static readonly HttpClient client = new HttpClient();

        // GET: /<controller>/
        public IActionResult Index()
        {
            var r = getList();
            
            return View("../List/Index", r.Result);
        }

        private async Task<IEnumerable<Internship>> getList()
        {

            HttpResponseMessage result = await client.GetAsync("https://localhost:3001/api/internship");
            var jsonString = result.Content.ReadAsStringAsync();

            IEnumerable<Internship> model = JsonConvert.DeserializeObject<IEnumerable<Internship>>(jsonString.Result);

            return model;
        }

    }
}

Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using webapp.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace webapp.Controllers
{
    public class ProfileController : Controller
    {
        static readonly HttpClient client = new HttpClient();
        // GET: /Profile

        [HttpGet]
        public ActionResult Index()
        {
            int uId =(int) HttpContext.Session.GetInt32("UserId");


            var r = getUser(uId);

            ViewBag.Data = "ID: "+uId;

            //TempData["UserMessage"] = new AppMessage() { CssClassName = "alert-danger  alert-dismissible", Title = "Error", Message = "Onjuiste combinatie van email en wachtwoord." };
            return View(r.Result);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(User u)
        {
           

            var r = await updateUserdata(u);

            if (r.IsSuccessStatusCode)
                return View("Index", u);

            TempData["UserMessage"] = new AppMessage() { CssClassName = "alert-danger  alert-dismissible", Title = "Error:", Message = " Fout tijdens opslaan gegevens! Probeer het opnieuw" };
            return View("Index");

        }
        private async Task<User> getUser(int id)
        {
           
            HttpResponseMessage result = await client.GetAsync("https://localhost:3001/api/user/"+ id);
            var jsonString = result.Content.ReadAsStringAsync();

            User model = JsonConvert.DeserializeObject<User>(jsonString.Result);

            return model;
        }

        private async Task<HttpResponseMessage> updateUserdata(User u)
        {

            string loginJson = JsonConvert.SerializeObject(new { u.FirstName, u.MiddleName, u.LastName, u.Email, u.Password });
            StringContent content = new StringContent(loginJson, Encoding.UTF8, "application/json");
            HttpResponseMessage result = await client.PutAsync("https://localhost:3001/api/user/" + HttpContext.Session.GetInt32("UserId"), content);
            var jsonString = result.Content.ReadAsStringAsync();

            //User model = JsonConvert.DeserializeObject<User>(jsonString.Result);


            return result;
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="nl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - App</title>
    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/css/fontawesome.css" />
    <link rel="stylesheet" href="/css/style.css" />
    @RenderSection("StyleSheets", required: false)
</head>
<body>
    <div class="dashboard">
        <header class="dbHeader">
            <h2>Stagesysteem</h2>
        </header>
        <div class="dbContainer">

            <div class="dbSidebar">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link active" asp-controller="Dashboard" asp-action="Index"><i class="fas fa-home"></i> Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Profile" asp-action="Index"><i class="fas fa-id-card"></i> Mijn profiel</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Internship" asp-action="Index"><i class="fas fa-list"></i> Stageplekken</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Internship" asp-action="Index"><i class="fas fa-calendar-day"></i> Werkstaten</a>
                    </li>
                </ul>
                <ul class="nav adminNav flex-column">
                    <li class="nav-item">
                        <h6><i class="fas fa-cogs"></i> Administrator</h6>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Profile" asp-action="Admin"><i class="fas fa-envelope"></i> Berichten</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Internship" asp-action="Admin"><i class="fas fa-users"></i> Gebruikers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Internship" asp-action="Admin"><i class="fas fa-calendar-day"></i> Werkstaten beheren</a>
                    </li>
                </ul>
            </div>
            <main class="dbMain">
                @RenderBody()
            </main>
        </div>
    </div>

    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/js/site.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>